name: Pull Request Tests

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:
      - uses: actions/checkout@v3
        run: Checkout ${{ github.head_ref }}
    
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      
      - name: Install Packages
        run: npm ci

      - name: Run Tests
        run: npm run test